makes 'install' target work as expected

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -29,7 +29,7 @@ distdir		:= @PACKAGE_NAME@-@PACKAGE_VERSION@
 mandatory	:= Prague Babylon Fresco Berlin 
 optional	:= GGI SDL Clients-C++ Clients-Python Clients-Java Clients-Perl
 
-ifneq (,$(findstring config, $(MAKECMDGOALS)))
+ifneq (,$(findstring config install, $(MAKECMDGOALS)))
 mandatory_dirs	:= $(foreach package, $(mandatory), $(shell test -d $(srcdir)/$(package) && echo '$(package)'))
 optional_dirs	:= $(foreach package, $(optional), $(shell test -d $(srcdir)/$(package) && echo '$(package)'))
 else
@@ -73,13 +73,21 @@ depend:
 doc:	config
 	$(MAKE) action="doc"
 
+# this target command needs some explanation:
+# * attempt to configure, build, and install all subdirs
+# * if an optional one fails, skip silently
+# * else bail out
 install:
 	for subdir in $(subdirs); do \
 	  echo "configuring package $$subdir with $(configure_args)";\
-	  (cd $$subdir && $(srcdir)/$$subdir/configure $(configure_args));\
-	  echo "making install in $$subdir";\
-	  $(MAKE) -C $$subdir install; \
-          done;
+	  (mkdir -p $$subdir && \
+	   cd $$subdir && \
+           $(srcdir)/$$subdir/configure $(configure_args) && \
+	   echo "making install in $$subdir" && \
+	   $(MAKE) install) || \
+           `echo "$(optional_dirs)" | grep -c $$subdir -` || \
+	   case "$(MFLAGS)" in *k*) fail=yes;; *) exit 1;; esac; \
+        done && test -z "$$fail"
 
 install-doc:	config
 	$(MAKE) action="install-doc"
